// File generated by FlutterFire CLI / Kenticket auto-config.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMeNfmV8Yz0C7DKZ-irSQG2WnxYTeYHUY',
    appId: '1:1007565664646:web:9a83d98b9bbb4b23e03c07',
    messagingSenderId: '1007565664646',
    projectId: 'kenticket-bioskop',
    authDomain: 'kenticket-bioskop.firebaseapp.com',
    storageBucket: 'kenticket-bioskop.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOkqpTac5uKe7GLDwje6tBBouQPzASRXQ',
    appId: '1:1007565664646:android:0cc2bed226f5fbbee03c07',
    messagingSenderId: '1007565664646',
    projectId: 'kenticket-bioskop',
    storageBucket: 'kenticket-bioskop.firebasestorage.app',
  );
}
